"""
本地期刊影响因子数据库（2024年常见SCI期刊）
来源：Journal Citation Reports (JCR)
"""
from typing import Optional, List, Dict

JOURNAL_IF_DATABASE = {
    'nature': 64.8,
    'science': 63.7,
    'cell': 66.8,
    'nature medicine': 87.2,
    'nature biotechnology': 73.5,
    'nature materials': 41.2,
    'nature nanotechnology': 40.5,
    'science': 63.7,
    'cell': 66.8,
    'nature genetics': 30.8,
    'nature immunology': 32.4,
    'nature chemistry': 11.4,
    'nature physics': 19.1,
    'lancet': 202.7,
    'lancet infectious diseases': 58.7,
    'lancet oncology': 51.1,
    'new england journal of medicine': 176.0,
    'jama': 157.3,
    'jama oncology': 28.4,
    'jama network open': 13.8,
    'bmj': 105.7,
    'bmj open': 4.1,
    'plos medicine': 15.8,
    'plos one': 3.7,
    'nature communications': 16.6,
    'scientific reports': 4.7,
    'cell reports': 9.4,
    'cell reports medicine': 16.0,
    'pnas': 11.1,
    'proceedings of the national academy of sciences': 11.1,
    'jacs': 15.0,
    'journal of the american chemical society': 15.0,
    'angewandte chemie': 15.0,
    'chemical reviews': 62.1,
    'chemical society reviews': 46.2,
    'energy & environmental science': 39.7,
    'nature energy': 49.7,
    'joule': 40.0,
    'advanced materials': 32.0,
    'advanced energy materials': 27.8,
    'acs nano': 17.1,
    'nano letters': 9.6,
    'acs catalysisysis': 13.7,
    'environmental science & technology': 11.4,
    'water research': 13.4,
    'isprs journal of photogrammetry and remote sensing': 12.7,
    'remote sensing of environment': 13.5,
    'international journal of remote sensing': 3.8,
    'ieee transactions on geoscience and remote sensing': 8.2,
    'ieee geoscience and remote sensing letters': 4.4,
    'computers & geosciences': 5.6,
    'geophysical research letters': 4.1,
    'journal of geophysical research': 3.8,
    'earth and planetary science letters': 4.5,
    'nature geoscience': 21.4,
    'science advances': 13.6,
    'nature climate change': 28.9,
    'environmental research letters': 6.9,
    'climate dynamics': 3.8,
    'global change biology': 9.0,
    'ecology letters': 11.8,
    'conservation biology': 5.4,
    'biological conservation': 5.5,
    'plos biology': 9.8,
    'current biology': 9.4,
    'e Life': 7.7,
    'pnas': 11.1,
    'journal of cell biology': 8.4,
    'molecular cell': 17.3,
    'cell metabolism': 29.0,
    'cell stem cell': 25.0,
    'immunity': 32.4,
    'cell host & microbe': 29.4,
    'nucleic acids research': 19.1,
    'genome research': 9.4,
    'genome biology': 13.8,
    'bioinformatics': 6.9,
    'plos computational biology': 4.8,
    'nature methods': 48.0,
    'nature protocols': 14.9,
    'scientific data': 9.8,
    'ieee transactions on pattern analysis and machine intelligence': 24.3,
    'international journal of computer vision': 19.5,
    'computer vision and image understanding': 4.2,
    'pattern recognition': 8.0,
    'ieee transactions on neural networks and learning systems': 10.4,
    'neural networks': 9.6,
    'neurocomputing': 6.0,
    'expert systems with applications': 8.5,
    'information sciences': 8.1,
    'knowledge-based systems': 8.1,
    'artificial intelligence': 9.0,
    'ieee transactions on knowledge and data engineering': 8.7,
    'ieee transactions on industrial informatics': 12.3,
    'ieee transactions on industrial electronics': 7.5,
    'ieee transactions on automation science and engineering': 9.4,
    'ieee robotics and automation letters': 5.6,
    'data mining and knowledge discovery': 4.5,
    'acm computing surveys': 14.8,
    'ieee communications surveys & tutorials': 35.6,
    'ieee journal on selected areas in communications': 11.2,
    'ieee transactions on communications': 6.1,
    'ieee wireless communications': 12.9,
    'ieee transactions on wireless communications': 6.8,
    'computer networks': 5.6,
    'ad hoc networks': 4.4,
    'sensors': 3.9,
    'ieee sensors journal': 4.3,
    'automation in construction': 10.3,
    'construction and building materials': 7.4,
    'journal of construction engineering and management': 3.3,
    'building and environment': 7.4,
    'energy and buildings': 6.6,
    'applied energy': 11.2,
    'energy': 6.0,
    'fuel': 7.4,
    'journal of power sources': 9.0,
    'electrochimica acta': 6.6,
    'journal of membrane science': 10.5,
    'desalination': 10.2,
    'chemical engineering journal': 15.1,
    'bioresource technology': 11.4,
    'biotechnology and bioengineering': 4.2,
    'biosensors and bioelectronics': 12.6,
    'talanta': 6.1,
    'analytica chimica acta': 6.2,
    'journal of chromatography a': 4.7,
    'food chemistry': 8.5,
    'journal of agricultural and food chemistry': 4.3,
    'nutrition research reviews': 8.7,
    'american journal of clinical nutrition': 9.3,
    'jama internal medicine': 21.0,
    'annals of internal medicine': 23.0,
    'circulation': 37.1,
    'journal of the american college of cardiology': 24.0,
    'european heart journal': 39.3,
    'heart rhythm': 6.0,
    'stroke': 7.8,
    'diabetes care': 16.2,
    'lancet diabetes & endocrinology': 44.5,
    'obesity reviews': 10.9,
    'gut': 31.8,
    'hepatology': 17.3,
    'gastroenterology': 29.4,
    'nature reviews gastroenterology & hepatology': 73.2,
    'annals of oncology': 52.4,
    'journal of clinical oncology': 45.4,
    'clinical cancer research': 13.8,
    'cancer research': 12.5,
    'oncogene': 8.0,
    'carcinogenesis': 5.0,
    'journal of the national cancer institute': 11.8,
    'radiology': 19.7,
    'medical physics': 7.0,
    'ieee transactions on medical imaging': 11.0,
    'neuroimage': 5.7,
    'biological psychiatry': 10.6,
    'molecular psychiatry': 17.0,
    'nature reviews neuroscience': 31.7,
    'neuron': 17.4,
    'journal of neuroscience': 6.0,
    'brain stimulation': 9.2,
    'stroke': 7.8,
    'journal of neural engineering': 5.4,
    'nature reviews drug discovery': 87.8,
    'drug discovery today': 8.0,
    'pharmacological reviews': 17.5,
    'clinical pharmacology & therapeutics': 6.0,
    'therapeutic drug monitoring': 3.2,
    'journal of clinical psychopharmacology': 3.0,
    'molecular psychiatry': 17.0,
    'translational psychiatry': 5.7,
    'psychiatry research': 4.9,
    'neuroscience & biobehavioral reviews': 7.8,
    'behaviour research and therapy': 4.7,
    'journal of consulting and clinical psychology': 4.3,
    'health psychology': 5.8,
    'social science & medicine': 5.4,
    'international journal of obesity': 4.9,
    'sleep medicine reviews': 10.5,
    'sleep': 5.6,
    'journal of sleep research': 3.4,
    'respiratory medicine': 4.8,
    'chest': 10.1,
    'thorax': 10.2,
    'american journal of respiratory and critical care medicine': 24.7,
    'european respiratory journal': 12.3,
    'pediatrics': 8.0,
    'jama pediatrics': 13.3,
    'nature pediatrics': 5.7,
    'obstetrics and gynecology': 7.0,
    'human reproduction': 6.1,
    'fertility and sterility': 7.0,
    'reproductive biomedicine online': 4.0,
    'age and ageing': 13.3,
    'journal of the american geriatrics society': 5.6,
    'age': 5.5,
    'ophthalmology': 14.3,
    'jama ophthalmology': 6.5,
    'invest ophthalmol vis sci': 4.4,
    'retina': 4.4,
    'american journal of ophthalmology': 5.0,
    'journal of urology': 6.0,
    'european urology': 24.3,
    'bju international': 4.6,
    'prostate': 4.0,
    'nephrology dialysis transplantation': 5.4,
    'kidney international': 10.1,
    'rheumatology': 5.5,
    'arthritis & rheumatology': 9.3,
    'annals of the rheumatic diseases': 27.4,
    'osteoporosis international': 4.0,
    'bone': 4.5,
    'journal of bone and mineral research': 6.2,
    'allergy': 14.7,
    'journal of allergy and clinical immunology': 10.3,
    'clinical and experimental allergy': 5.0,
    'immunology': 5.5,
    'european journal of immunology': 5.4,
    'journal of immunology': 5.4,
    'nature immunology': 32.4,
    'nature reviews immunology': 100.3,
    'blood': 25.5,
    'leukemia': 12.8,
    'haematologica': 7.0,
    'bone marrow transplantation': 4.0,
    'stem cells': 6.0,
    'stem cell reports': 5.0,
    'nature reviews molecular cell biology': 94.0,
    'current opinion in cell biology': 7.5,
    'trends in cell biology': 15.0,
    'cell research': 25.0,
    'molecular biology of the cell': 5.8,
    'journal of molecular biology': 5.6,
    'protein science': 5.0,
    'proteins': 4.4,
    'structure': 6.8,
    'journal of structural biology': 4.0,
    'acta crystallographica section d': 2.6,
    'acta crystallographica section a': 6.2,
    'journal of medicinal chemistry': 8.0,
    'pharmaceutical research': 5.0,
    'drug metabolism and disposition': 3.8,
    'molecular pharmaceutics': 5.0,
    'international journal of pharmaceutics': 5.8,
    'journal of controlled release': 10.8,
    'advanced drug delivery reviews': 17.9,
    'biomaterials': 15.0,
    'acta biomaterialia': 9.4,
    'biomaterials': 15.0,
    'tissue engineering part a': 4.2,
    'regenerative medicine': 4.2,
    'nature reviews materials': 56.7,
    'advanced functional materials': 19.0,
    'small': 13.0,
    'acs applied materials & interfaces': 9.4,
    'journal of materials chemistry a': 14.5,
    'nanoscale': 8.0,
    'nanomedicine': 6.0,
    'nano today': 17.4,
    'advanced science': 15.1,
    'materials today': 26.9,
    'materials science & engineering r-reports': 29.0,
    'progress in materials science': 37.6,
    'progress in polymer science': 31.1,
    'polymer': 4.9,
    'macromolecules': 5.5,
    'soft matter': 4.0,
    'langmuir': 4.0,
    'journal of colloid and interface science': 9.9,
    'advances in colloid and interface science': 15.0,
    'surface science reports': 15.0,
    'catalysis today': 5.8,
    'applied catalysis b-environmental': 22.1,
    'journal of catalysis': 7.5,
    'catalysis science & technology': 5.5,
    'chemical engineering science': 4.4,
    'industrial & engineering chemistry research': 3.8,
    'process safety and environmental protection': 6.4,
    'safety science': 6.3,
    'accidents analysis and prevention': 4.6,
    'journal of safety research': 3.2,
    'reliability engineering & system safety': 8.1,
    'ieee transactions on reliability': 5.5,
    'applied ergonomics': 3.5,
    'human factors': 4.5,
    'ergonomics': 2.6,
    'international journal of industrial ergonomics': 3.2,
    'journal of environmental management': 8.7,
    'journal of cleaner production': 11.1,
    'sustainability': 3.9,
    'sustainable cities and society': 8.5,
    'energy policy': 5.0,
    'renewable & sustainable energy reviews': 15.9,
    'applied energy': 11.2,
    'renewable energy': 8.9,
    'solar energy': 4.9,
    'wind energy': 4.0,
    'fuel cells': 2.8,
    'international journal of hydrogen energy': 8.0,
    'batteries': 4.0,
    'journal of power sources': 9.0,
    'ieee transactions on smart grid': 8.0,
    'applied thermal engineering': 6.2,
    'international journal of thermal sciences': 4.0,
    'energy conversion and management': 10.4,
    'building simulation': 4.5,
    'hvac&r research': 2.2,
    'international journal of refrigeration': 3.7,
    'proceedings of the combustion institute': 4.0,
    'combustion and flame': 5.4,
    'fuel': 7.4,
    'combustion science and technology': 2.5,
    'fire technology': 3.0,
    'fire safety journal': 2.8,
}

def get_impact_factor_from_db(journal_name: str) -> Optional[float]:
    """从本地数据库查询影响因子"""
    if not journal_name:
        return None
    
    journal_lower = journal_name.lower().strip()
    journal_normalized = journal_lower.replace('-', '').replace(' ', '')
    
    for name, if_value in JOURNAL_IF_DATABASE.items():
        name_normalized = name.replace('-', '').replace(' ', '')
        if name in journal_lower or journal_lower in name:
            return float(if_value)
        if name_normalized == journal_normalized:
            return float(if_value)
    
    return None

def normalize_journal_name(name: str) -> str:
    """标准化期刊名称"""
    if not name:
        return ''
    return name.strip().lower()

def search_journal_in_db(keyword: str) -> List[Dict[str, float]]:
    """模糊搜索期刊"""
    if not keyword or len(keyword) < 3:
        return []
    
    keyword = normalize_journal_name(keyword)
    results = []
    
    for name, if_value in JOURNAL_IF_DATABASE.items():
        if keyword in name:
            results.append({'journal_name': name, 'impact_factor': if_value})
    
    return results[:10]
